app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', 'IndexController@index');
Route::get('menu',['uses' => 'IndexController@menu', 'as' => 'index.menu']);
Route::get('home', 'HomeController@index');

Route::get('profile/view', ['middleware' => 'auth', 'uses' => 'ProfileController@viewProfile']);

Route::get('profile/view/{username}', 'ProfileController@viewUser');

Route::get('profile/edit', ['middleware' => 'auth', 'uses' => 'ProfileController@getEdit']);
Route::post('profile/edit', ['middleware' => 'auth', 'uses' => 'ProfileController@postEdit']);

Route::get('company/view/', ['middleware' => 'auth', 'uses' => 'CompanyController@viewMyCompany']);
Route::get('company/view/{id}', 'CompanyController@viewCompany');

Route::get('company/create', ['middleware' => 'auth', 'uses' => 'CompanyController@getCreate']);
Route::post('company/create', ['middleware' => 'auth', 'uses' => 'CompanyController@postCreate']);

Route::get('company/edit', ['middleware' => 'auth', 'uses' => 'CompanyController@getEdit']);
Route::post('company/edit', ['middleware' => 'auth', 'uses' => 'CompanyController@postEdit']);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::get('user/delete/{id}', ['middleware' => 'admin', 'uses' => 'UserController@getDelete']);
Route::get('user/active/{id}', ['middleware' => 'admin', 'uses' => 'UserController@getActive']);

Route::get('admin/accounts', 'AdminController@getAccounts');

Route::get('admin/company', ['middleware' => 'admin', 'uses' => 'AdminController@getCompanies', 'as' => 'company.index']);
Route::delete('admin/company/{id}', ['middleware' => 'admin', 'uses' => 'AdminController@destroyCompany', 'as' => 'company.destroy']);
Route::post('admin/company/{id}', ['middleware' => 'admin', 'uses' => 'AdminController@updateCompany', 'as' => 'company.update']);

Route::resource('city', 'CityController');
Route::resource('role', 'RoleController');
Route::resource('category', 'CategoryController');

Route::get('product/view/{id}', 'ProductController@viewProduct');

// Ratings
Route::post('rating/{product_id}', ['middleware' => 'auth', 'uses' => 'RatingController@create', 'as' => 'rating.create']);
Route::delete('rating/{rating_id}', ['middleware' => 'auth', 'uses' => 'RatingController@delete', 'as' => 'rating.delete']);

Route::get('product/create', ['middleware' => 'auth', 'uses' => 'ProductController@getCreate']);
Route::post('product/create', ['middleware' => 'auth', 'uses' => 'ProductController@postCreate']);

Route::get('product/edit/{id}', ['middleware' => 'auth', 'uses' => 'ProductController@getEdit']);
Route::post('product/edit/', ['middleware' => 'auth', 'uses' => 'ProductController@postEdit']);
Route::get('/product/delete/{id}', ['middleware' => 'auth', 'uses' => 'ProductController@getDelete']);
Route::delete('image/{id}', ['middleware' => 'auth', 'uses' => 'ImageController@destroy', 'as' => 'image.destroy']);
Route::get('product/', ['uses' => 'ProductController@index', 'as' => 'product.index']);

Route::get('/search', ['uses' => 'SearchController@index', 'as' => 'search.index']);

app/Product.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use CustomModel;

    use SoftDeletes;

    protected $table = 'product';

    protected $fillable = ['name', 'sh_description', 'l_description'];

    protected $hidden = [];

    public function delete() {
        //delete all associated prices
        $this->prices()->delete();
        //delete all associated ratings
        $this->ratings()->delete();
        //delete all images
        $this->images()->delete();
        parent::delete();
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    public function prices()
    {
        return $this->hasMany('App\Price');
    }

    public function images()
    {
        return $this->hasMany('App\Image');
    }

    public function ratings()
    {
        return $this->hasMany('App\Rating');
    }

    //Mapped tables (product & tag <=> many to many relationship)
    public function tags()
    {
        return $this->belongsToMany('App\Tag', 'product_has_tag');
    }

    public function getActivePriceAttributes() {
        return $this->prices()->where('active', '=', 1)->first();
    }
    
    public function ownedBy(User $user) {
        $usr_comp = $user->company()->first();
        $prd_comp =  $this->company()->first();
        return ($usr_comp && $usr_comp->id === $prd_comp->id);
    }
    
    public function getShowTagsAttribute() {
        $tags = $this->tags()->get();
        $res = '';
        foreach ($tags as $tag) {
            $res .= $tag->name . ',';
        }
        return $res;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Company;
use App\Gallery;
use App\Image;
use App\Price;
use App\Product;
use App\Rating;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;

class ProductController extends Controller
{
    /*
      |--------------------------------------------------------------------------
      | Welcome Controller
      |--------------------------------------------------------------------------
      |
      | This controller renders the "marketing page" for the application and
      | is configured to only allow guests. Like most of the other sample
      | controllers, you are free to modify or remove it as you desire.
      |
     */

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('guest');
    }

    public function index(Request $req) {
        if ($req->has('category')) {
            $cat_id = $req->input('category');
            $category = Category::findById($cat_id);
            $result = $category;
        } else if ($req->has('tag')) {
            $tag_id = $req->input('tag');
            $tag = Tag::findById($tag_id);
            $result = $tag;
        } else {
            Session::flash('message', 'Please specify a valid category or tag.');
            Session::flash('alert-class', 'alert-danger');
            return redirect('/');
        }
        if (!$result) {
            Session::flash('message', 'The specified category or tag does not exist!');
            Session::flash('alert-class', 'alert-danger');
            return redirect('/');
        }
        if (!$result->products || $result->products->isEmpty()) {
            Session::flash('message', 'There are no products in the "' . $result->name .'" ' . $result->getTable() . '!');
            Session::flash('alert-class', 'alert-danger');
            return redirect('/');
        }
        return view('product.list')->with(['result' => $result]);
    }

    /**
     * Show the application welcome screen to the user.
     *
     * @return Response
     */
    public function viewProduct($id)
    {
        $categories = Category::all();
        $ratings = Rating::all();
        $product = Product::findById($id);

        if (!$product) {
            Session::flash('message', 'Product with selected id does not exists');
            Session::flash('alert-class', 'alert-danger');
            return redirect('/');
        }
        return view('product.index')->with(['product' => $product, 'categories' => $categories, 'ratings' => $ratings]);
    }

    public function getCreate()
    {
        $categories = Category::all();
        $products = Product::all();
        $prices = Price::all();

        if (Auth::check()) {
            $user = Auth::getUser();
        }
        $company = $user->company()->first();
        if (!$company) {
            Session::flash('message', 'You need a company to add products');
            Session::flash('alert-class', 'alert-info');
            return redirect('/company/create');
        }
        return view('product.create')->with(['user' => $user, 'categories' => $categories, 'products' => $products, 'prices' => $prices]);
    }

    private function uploadImage($file, Product $product)
    {
        $destinationPath = public_path() . getenv('UPLOADS_DIR') . getenv('PRODUCTS_IMAGES_DIR') . $product->id . '/';
        $extension = $file->getClientOriginalExtension(); // getting image extension
        $fileName = md5($product->name) . rand(11111, 99999) . '.' . $extension; // renaming image
        $file->move($destinationPath, $fileName);
        return $fileName;
    }
    
    public function create_tags($tags_str) {
        $tags = explode(",",$tags_str);
        $res = [];
        foreach ($tags as $tag) {
            $res[] = Tag::firstOrCreate(['name'=>Str::lower($tag)]);
        }
        return $res;
    }

    public function postCreate(Request $req)
    {

        $this->validate($req, [
            'name' => 'required',
            'price' => 'required|numeric',
            'sh_description' => 'required',
            'l_description' => 'required',
            'sh_description' => 'required',
            'tags'=>'required'
        ]);
        
        $tags = $this->create_tags($req->input('tags'));
        $company_id = $req->input('company');
        $company = Company::findById($company_id);

        $category_id = $req->input('category');
        $category = Category::findById($category_id);

        $product = new Product([
            'name' => $req->input('name'),
            'sh_description' => $req->input('sh_description'),
            'l_description' => $req->input('l_description'),
            ]);
        $product->prices();
        $product->company()->associate($company);
        $product->category()->associate($category);
        $product->save();
        foreach ($tags as $tag) {
            $product->tags()->attach($tag);
        }
        $product->push();

        $price = new Price(['price' => $req->input('price'), 'active' => 1]);
        $price->product()->associate($product);
        $price->save();

        $files = $req->file('images');
        $files_count = count($files);
        foreach ($files as $file) {
            if (!empty($file) && $file->isValid()) {
                $image = new Image([
                    'path' => $this->uploadImage($file, $product)
                ]);
                $image->product()->associate($product);
                $image->save();
            }
        }
        Session::flash('message', 'Product created with success');
        Session::flash('alert-class', 'alert-success');
        return redirect('product/view/' . $product->id);
    }

    public function getEdit($id)
    {
        $categories = Category::all();
        $product = Product::findById($id);
        if (Auth::check()) {
            $user = Auth::getUser();
        }
        if (!$product->ownedBy($user)) {
            Session::flash('message', 'You are not allowed to edit this product!');
            Session::flash('alert-class', 'alert-danger');
            return redirect('/');
        }
        return view('product.edit')->with(['categories' => $categories, 'product' => $product]);

    }

    public function postEdit(Request $req)
    {
        $this->validate($req, [
            'name' => 'required',
            'price' => 'required|numeric',
            'sh_description' => 'required',
            'l_description' => 'required',
            'sh_description' => 'required',
        ]);

        $id = intval($req->input('id'));
        $product = Product::findById($id);
        if (Auth::check()) {
            $user = Auth::getUser();
        }
        if (!$product->ownedBy($user)) {
            Session::flash('message', 'You are not allowed to edit this product!');
            Session::flash('alert-class', 'alert-danger');
            return redirect('/');
        }
        $product->name = $req->input('name');
        $product->sh_description = $req->input('sh_description');
        $product->l_description = $req->input('l_description');

        $old_tags = $product->tags()->get();
        foreach ($old_tags as $old_tag) {
            $product->tags()->detach($old_tag);
        }
        $product->push();
        $tags = $this->create_tags($req->input('tags'));
        foreach ($tags as $tag) {
            $product->tags()->attach($tag);
        }
        $product->push();
        
        
        $price_val = $req->input('price');
        $price = $product->prices()->first();
        $price->price = $price_val;
        $price->save();

        $category_id = $req->input('category');
        $category = Category::where('id', '=', $category_id)->first();

        $product->category()->associate($category);

        $product->save();
        foreach ($product->images() as $image) {
            $image->delete();
        }
        $files = $req->file('images');
        $files_count = count($files);
        foreach ($files as $file) {
            if (!empty($file) && $file->isValid()) {
                $image = new Image([
                    'path' => $this->uploadImage($file, $product)
                ]);
                $image->product()->associate($product);
                $image->save();
            }
        }
        Session::flash('message', 'Product edited with success');
        Session::flash('alert-class', 'alert-success');
        return redirect('product/view/' . $product->id);
    }

    public function getDelete($id)
    {
        $product = Product::findById($id);
        if (Auth::check()) {
            $user = Auth::getUser();
        }
        if (!$product->ownedBy($user)) {
            Session::flash('message', 'You are not allowed to delete this product!');
            Session::flash('alert-class', 'alert-danger');
            return redirect('/');
        }
        $product->delete();
        Session::flash('message', 'Product was deleted with success');
        Session::flash('alert-class', 'alert-success');
        return redirect('/company/view/');
    }
}

resources/views/product/create.blade.php
@extends('layouts.master')
@section('title')
Add new Product
@stop
@section('content')

<div class="profile-user-stuff"> <!-- .profile-user-stuff -->
    <div class="container">
        <div class="row">

            <div class="col-sm-6 col-centered">
                @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>There were some problems with your input.</strong><br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                <div class="profile-personal-info">
                    <form id="validate-form" action="{{url('product/create')}}" method="POST"
                          enctype="multipart/form-data">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="company" value="{{ Auth::user()->company->id }}">

                        <div class="form-group">
                            <label for="name">* Product Name</label>
                            <input type="text" class="form-control" id="name"
                                   name="name" placeholder="Product Name" required>
                        </div>

                        <div class="form-group">
                            <label for="price">* Price</label>

                            <div class="input-icon">
                                <input type="text" name="price" class="form-control" aria-label="Çmimi">
                                <span class="glyphicon glyphicon-euro" aria-hidden="true"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="sh_description">* Short description</label>
                            <textarea class="form-control" rows="3" name="sh_description"
                                      placeholder="Product Description"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="l_description">* Long Description</label>
                            <textarea class="form-control" rows="3" name="l_description"
                                      placeholder="Product Description"></textarea>
                        </div>
                        
                        <div class="form-group">
                            <label for="name">* Product Tags</label>
                            <p>Separate tags using enter, tab or comma.</p>
                            <input type="text" class="form-control" id="tags"
                                   name="tags" placeholder="Tags" value="" required data-role="tagsinput">
                        </div>

                        <div class="form-group">
                            <label for="input-image">* Images</label>
                            {!! Form::file('images[]', array('multiple'=>true)) !!}
                        </div>

                        <fieldset>
                            <div class="form-group">
                                <label for="category">* Chose Category</label>
                                <select id="category" class="form-control" name="category">
                                    @foreach ($categories as $category)
                                    <option value="{{$category->id}}" {{($category->name == 'name')? 'selected' : ''}}>
                                        {{$category->name}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                        </fieldset>

                        <button type="submit" class="btn btn-default">Publish Product</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/product/edit.blade.php
@extends('layouts.master')
@section('title')
Edit Product
@stop
@section('content')

<div class="profile-user-stuff"> <!-- .profile-user-stuff -->
    <div class="container">
        <div class="row">
                
            <div class="col-sm-6 col-centered">
                @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <strong>There were some problems with your input.</strong><br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                
                <div class="profile-personal-info">
    <form id="validate-form" action="{{url('product/edit')}}" method="POST" enctype="multipart/form-data">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="company" value="{{ Auth::user()->company->id }}">

                        <input type="hidden" name="id" value="{{$product->id}}">

                        <div class="form-group">
                            <label for="name">* Product Name</label>
                            <input type="text" class="form-control" id="name"
                                   name="name" placeholder="Product Name" required value="{{ $product->name }}">
                        </div>

                        <div class="form-group">
                            <label for="price">* Price</label>
                            <div class="input-icon">
                                <input type="text" name="price" class="form-control" aria-label="Price" value="{{$product->getActivePriceAttributes()->price}}">
                                <span class="glyphicon glyphicon-euro" aria-hidden="true"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="sh_description">* Short description</label>
                            <textarea class="form-control" rows="3" name="sh_description" 
                                      placeholder="Product Description">{{$product->sh_description}}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="l_description">* Long Description</label>
                            <textarea class="form-control" rows="3" name="l_description" 
                                      placeholder="Product Description">{{$product->l_description}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="name">* Product Tags</label>
                            <p>Separate tags using enter, tab or comma.</p>
                            <input type="text" class="form-control" id="tags"
                                   name="tags" placeholder="Tags" value="{{ $product->show_tags }}" required data-role="tagsinput">
                        </div>
                        <div class="form-group">
                            <label for="input-image">* Images</label>
                            {!! Form::file('images[]', array('multiple'=>true)) !!}

                            <ul class="prev-images">
                                @foreach ($product->images as $image)
                                <li>
                                    <div class="see-if-this-gets-removed">
                                        <a href="#" class="remove-img glyphicon glyphicon-remove"
                                           data-image="{{ $image->id }}"
                                           data-token="{{ csrf_token() }}" data-url="/image/{{ $image->id }}"
                                           onclick="remove_image(this)"></a>

                                        <div class="img-container">
                                            <img src="{{ $image->url }}" alt="Product"/>
                                        </div>

                                </li>
                                @endforeach
                            </ul>
                        </div>

                        <fieldset>
                            <div class="form-group">
                                <label for="category">* Choose Category</label>
                                <select id="category" class="form-control" name="category">
                                    @foreach ($categories as $category)
                                    <option value="{{$category->id}}" {{($category->id == $product->category_id)? 'selected' : ''}}>
                                        {{$category->name}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                        </fieldset>
                        <button type="submit" class="btn btn-default">Save</button>
                        <a href="#" class="btn btn-danger delete-btn" data-toggle="modal" data-target="#deleteConfirm">Delete</a>
                    </form>

                    <script>

                        function remove_image (elem) {
                            var image_id = $(elem).data('image');
                            $.ajax({
                                url: $(elem).data('url'),
                                type: 'POST',
                                data: {
                                    _method: 'DELETE',
                                    _token: $(elem).data('token')
                                },
                                success: function (result) {
                                    console.log(result);
                                    $(elem).parent().remove()
                                }
                            });

                        }
                    </script>
                    
                    <!-- Modal -->
                    <div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">Delete {{ $product->name }}</h4>
                                </div>
                                <div class="modal-body">
                                    Are you sure you wanna delete "{{ $product->name }}" ? <br>
                                    This action can not be undone.
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    <a href="/product/delete/{{$product->id}}" class="btn btn-danger delete-btn">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/product/index.blade.php
@extends('layouts.master')
@section('title')
    {{ $product->name }}
@stop

@section('content')
    <div class="container">

        <div class="row">
            <div class="col-sm-7">
                <ul class="product-gallery">
                    @if ($product->images->isEmpty())
                        <li>
                            <img src="/repository/images/img_placeholder.png" alt="Product">
                        </li>
                    @endif
                    @foreach ($product->images as $image)
                        <li>
                            <img src="{{ $image->url }}" alt="Product">
                        </li>
                    @endforeach
                </ul>
            </div>

            <div class="col-sm-5">
                <div class="current-product-description">
                    <h2>{{ $product->name }}</h2>
                    <input type="hidden" class="rating" readonly="readonly" value="{{$product->ratings()->avg('rating')}}">
                    <p class="current-cost"><span class="money-type">$</span> {{ $product->getActivePriceAttributes()->price
                    }}</p>

                    <h3>Quick overview: </h3>

                    <p>
                        {{$product->sh_description}}
                    </p>
                </div>
                @if (Auth::check() && $product->ownedBy(Auth::user()))
                    <a href="/product/edit/{{ $product->id }}" class="btn btn-default"><span
                                class="glyphicon glyphicon-edit"></span> Edit product</a>
                @endif
                <div class="tags">
                    <h2>Tags</h2>
                    <ul>
                    @foreach($product->tags as $tag)
                        <li><a href="{{ URL::route('product.index', ['tag'=>$tag->id]) }}">{{$tag->name}}</a></li>
                    @endforeach    
                    </ul>
                </div>
            </div>
            <div class="col-sm-12">
                <h2>Long Description</h2>

                <p>{{$product->l_description}}</p>
            </div>
            <div class="col-sm-10">

                @if(Auth::check() && (!Auth::user()->ratingFor($product->id)))
                <h2>Review</h2>
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>There were some problems with your input.</strong><br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="well well-sm">
                    <div class="row" id="post-review-box">
                        <!-- Rating Section -->
                            <div class="col-md-12">
                            {!! Form::open(['route' => ['rating.create', $product->id], 'method' => 'post']) !!}
                                <input type="hidden" name="rating" data-fractions="2" class="js-rating"/>
                                <textarea class="form-control" cols="50" id="new-review" name="comment"
                                      placeholder="Enter your review here..." rows="5"></textarea>
                                <button class="btn btn-default star-btn" type="submit">Publish Review</button>
                            {!! Form::close() !!}
                            </div>
                         <!-- End of Rating Section-->
                    </div>
                </div>
                @endif

                <div class="review-list">
                    <h2>Customer Reviews</h2>

                        <ul>
                            @foreach($product->ratings as $rating)
                                <li>
                                    @if (Auth::check() && (Auth::user()->id === $rating->user->id))
                                        {!! Form::open(['route' => ['rating.delete', $rating->id],
                                        'method' => 'delete']) !!}
                                        <button type="submit" title="Delete your comment and rating"
                                                    class="delete-confirm delete-comment glyphicon glyphicon-remove">
                                        </button>
                                        {!! Form::close() !!}
                                    @endif
                                    <span class="user">{{ $rating->user->username }}</span>
                                    <input type="hidden" class="rating" readonly="readonly" value="{{$rating->rating}}">
                                    <p>{{$rating->comment}}</p>
                                </li>
                            @endforeach
                        </ul>
                </div>
            </div>

            <div class="col-sm-2">
                <img src="/repository/images/ad_placeholder.jpg" alt="potencial commercial user"/>
            </div>
        </div>
    </div>
@stop