app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', 'IndexController@index');
Route::get('menu',['uses' => 'IndexController@menu', 'as' => 'index.menu']);
Route::get('home', 'HomeController@index');

Route::get('profile/view', ['middleware' => 'auth', 'uses' => 'ProfileController@viewProfile']);

Route::get('profile/view/{username}', 'ProfileController@viewUser');

Route::get('profile/edit', ['middleware' => 'auth', 'uses' => 'ProfileController@getEdit']);
Route::post('profile/edit', ['middleware' => 'auth', 'uses' => 'ProfileController@postEdit']);

Route::get('company/view/', ['middleware' => 'auth', 'uses' => 'CompanyController@viewMyCompany']);
Route::get('company/view/{id}', 'CompanyController@viewCompany');

Route::get('company/create', ['middleware' => 'auth', 'uses' => 'CompanyController@getCreate']);
Route::post('company/create', ['middleware' => 'auth', 'uses' => 'CompanyController@postCreate']);

Route::get('company/edit', ['middleware' => 'auth', 'uses' => 'CompanyController@getEdit']);
Route::post('company/edit', ['middleware' => 'auth', 'uses' => 'CompanyController@postEdit']);

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::get('user/delete/{id}', ['middleware' => 'admin', 'uses' => 'UserController@getDelete']);
Route::get('user/active/{id}', ['middleware' => 'admin', 'uses' => 'UserController@getActive']);

Route::get('admin/accounts', 'AdminController@getAccounts');

Route::get('admin/company', ['middleware' => 'admin', 'uses' => 'AdminController@getCompanies', 'as' => 'company.index']);
Route::delete('admin/company/{id}', ['middleware' => 'admin', 'uses' => 'AdminController@destroyCompany', 'as' => 'company.destroy']);
Route::post('admin/company/{id}', ['middleware' => 'admin', 'uses' => 'AdminController@updateCompany', 'as' => 'company.update']);

Route::resource('city', 'CityController');
Route::resource('role', 'RoleController');
Route::resource('category', 'CategoryController');

Route::get('product/view/{id}', 'ProductController@viewProduct');

// Ratings
Route::post('rating/{product_id}', ['middleware' => 'auth', 'uses' => 'RatingController@create', 'as' => 'rating.create']);
Route::delete('rating/{rating_id}', ['middleware' => 'auth', 'uses' => 'RatingController@delete', 'as' => 'rating.delete']);

Route::get('product/create', ['middleware' => 'auth', 'uses' => 'ProductController@getCreate']);
Route::post('product/create', ['middleware' => 'auth', 'uses' => 'ProductController@postCreate']);

Route::get('product/edit/{id}', ['middleware' => 'auth', 'uses' => 'ProductController@getEdit']);
Route::post('product/edit/', ['middleware' => 'auth', 'uses' => 'ProductController@postEdit']);
Route::get('/product/delete/{id}', ['middleware' => 'auth', 'uses' => 'ProductController@getDelete']);
Route::delete('image/{id}', ['middleware' => 'auth', 'uses' => 'ImageController@destroy', 'as' => 'image.destroy']);
Route::get('product/', ['uses' => 'ProductController@index', 'as' => 'product.index']);

Route::get('/search', ['uses' => 'SearchController@index', 'as' => 'search.index']);

app/Company.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\File;

class Company extends Model
{
    use CustomModel;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'company';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'address', 'logo_image', 'web_address', 'slogan',
        'email', 'description', 'telephone'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];


    public function delete()
    {
        // delete all associated products
        $this->products()->delete();
        // delete image
        $image = public_path() . $this->getLogoImageLinkAttribute();
        if (File::isFile($image)) {
            File::delete($image);
        }
        parent::delete();

    }


    public function city()
    {
        return $this->belongsTo('App\City');
    }

    public function owner()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function isOwner(User $user)
    {
        return ($this->owner()->first()->id === $user->id);
    }

    public function products()
    {
        return $this->hasMany('App\Product');
    }

    public function getLogoImageLinkAttribute()
    {
        return getenv('UPLOADS_DIR') . $this->logo_image;
    }
}

app/Image.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;

class Image extends Model
{

    use CustomModel;

    public $timestamps = false;
    protected $table = 'image';
    protected $fillable = ['path'];
    protected $hidden = [];

    public function getUrlAttribute()
    {
        $destinationPath = getenv('UPLOADS_DIR') . getenv('PRODUCTS_IMAGES_DIR') . $this->product()->first()->id . '/';
        return $destinationPath . $this->path;
    }

    public function product()
    {
        return $this->belongsTo('App\Product');
    }

    public function deleteFromDisk() {
        $file = public_path() . getenv('UPLOADS_DIR') . getenv('PRODUCTS_IMAGES_DIR') . $this->product()->first()->id . '/' . $this->path;
        return $file;
        if (File::isFile($file)) {
            File::delete();
        }
    }

}

app/Http/Controllers/SearchController.php
<?php namespace App\Http\Controllers;

use App\Category;
use App\Company;
use App\Product;
use App\Tag;
use App\User;
use Illuminate\Http\Request;

class SearchController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Home Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders your application's "dashboard" for users that
	| are authenticated. Of course, you are free to change or remove the
	| controller as you wish. It is just here to get your app started!
	|
	*/

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
	}

	/**
	 * Show the application dashboard to the user.
	 *
	 * @return Response
	 */
	public function index(Request $req)
	{
		$this->validate($req, [
             'query'  => 'required|min:3',
		]);
		$query = preg_replace('[%_]', '', strip_tags($req->input('query')));
		$products = Product::where('name', 'LIKE', "%$query%")->get();
		$categories = Category::where('name', 'LIKE', "%$query%")->get();
		$tags = Tag::where('name', 'LIKE', "%$query%")->get();
		$companies = Company::where('name', 'LIKE', "%$query%")->get();
		$users = User::where('username', 'LIKE', "%$query%")->get();

		$total = 	$products->count() +
					$categories->count() +
					$tags->count() +
					$companies->count() +
					$users->count();

		return view('search.index')->with([
			'products'=>$products,
			'categories'=>$categories,
			'tags'=>$tags,
			'companies'=>$companies,
			'users'=>$users,
			'total'=>$total,
		]);
	}

}

resources/views/search/index.blade.php
@extends('layouts.master')

@section('title', 'Home')

@section('content')
<h2 class="result-title">You query returned {{ $total }} results!</h2>

@if (!$products->isEmpty())
<div class="title">
    <h2>Products</h2>
</div>

<div class="row">
    @foreach ($products as $product)
    <div class="col-sm-3">
        <div class="post">
            <a href="/product/view/{{ $product->id }}">
                @if ($product->images->isEmpty())
                <img src="/repository/images/img_placeholder.png" alt="img" class="img-responsive">
                @else
                <img src="{{ $product->images->first()->url }}" alt="img" class="img-responsive">
                @endif
            </a>

            <div class="description">
                <h3><a href="/product/view/{{ $product->id }}">{{ $product->name }}</a></h3>
                @foreach ( $product->prices as $price)
                @if ($price->active)
                <h4><a href="/product/view/{{$product->id}}">{{ $price->price."$" }}</a></h4>
                @endif
                @endforeach
            </div>
        </div>
    </div>
    @endforeach
</div>
@endif


@if (!$categories->isEmpty())
<div class="title">
    <h2>Categories</h2>
</div>

<div class="row">
    @foreach ($categories as $cat)
    <div class="col-sm-3">
        <div class="post">
            <div class="description">
                <h3><a href="#">{{ $cat->name }}</a></h3>
            </div>
        </div>
    </div>
    @endforeach
</div>
@endif


@if (!$tags->isEmpty())
<div class="title">
    <h2>Tags</h2>
</div>

<div class="row">
    @foreach ($tags as $tag)
    <div class="col-sm-3">
        <div class="post">
            <div class="description">
                <h3><a href="#">{{ $tag->name }}</a></h3>
            </div>
        </div>
    </div>
    @endforeach
</div>
@endif


@if (!$companies->isEmpty())
<div class="title">
    <h2>Companies</h2>
</div>

<div class="row">
    @foreach ($companies as $comp)
    <div class="col-sm-3">
        <div class="post">
            <a href="/company/view/{{ $comp->id }}">
                @if (!$comp->logo_image)
                <img src="/repository/images/img_placeholder.png" alt="img" class="img-responsive">
                @else
                <img src="{{ $comp->logo_image_link }}" alt="img" class="img-responsive">
                @endif
            </a>

            <div class="description">
                <h3><a href="/company/view/{{ $comp->id }}">{{ $comp->name }}</a></h3>
            </div>
        </div>
    </div>
    @endforeach
</div>
@endif


@if (!$users->isEmpty())
<div class="title">
    <h2>Users</h2>
</div>

<div class="row">
    @foreach ($users as $user)
    <div class="col-sm-3">
        <div class="post">
            <a href="/profile/view/{{ $user->id }}">
                <img src="{{ $user->gravatar }}" alt="img" class="img-responsive">
            </a>

            <div class="description">
                <h3><a href="/profile/view/{{ $user->id }}">{{ $user->username }}</a></h3>
            </div>
        </div>
    </div>
    @endforeach
</div>
@endif



@stop